Cloudflare: Use name parameter to avoid obtaining unnecessary permiss…
NewFuture/DDNS pull request #206
Opened 2020-09-14 18:05 UTC by imbillow

…ions

2020-09-15 03:34 UTC, NewFuture commented
@tongyifan @cnwangjihe  有空帮忙 review 一下

2020-09-15 06:58 UTC, tongyifan requested changes

2020-09-15 06:58 UTC, tongyifan commented on dns/cloudflare.py
> +    return zones[0]["id"]
当域名不存在时，原有代码将返回None，修改后代码将报错

2020-09-15 06:58 UTC, tongyifan commented on dns/cloudflare.py
> +    zones = request('GET', '', {"name": get_level1_domain(domain)}, per_page=50)
建议直接写为
```python
zones = request('GET', '', name=get_level1_domain(domain), per_page=50)
```

2020-09-15 12:58 UTC, imbillow commented on dns/cloudflare.py
> +    return zones[0]["id"]
这样处理可以吗？

2020-09-20 01:33 UTC, closed without merging

2020-09-20 05:38 UTC, NewFuture commented
咋 close 了？

2020-10-11 19:55 UTC, imbillow commented
懒